import {
  faAlignLeft,
  faArrowsSpin,
  faBolt,
  faBroom,
  faCode,
  faComments,
  faComputer,
  faCubes,
  faDiagramProject,
  faImage,
  faImages,
  faLanguage,
  faNetworkWired,
  faPaintbrush,
  faPalette,
  faPenRuler,
  faRobot,
  faWandMagicSparkles,
} from '@fortawesome/free-solid-svg-icons'
import {
  faAws,
  faBootstrap,
  faCss3Alt,
  faDocker,
  faFigma,
  faGitAlt,
  faHtml5,
  faJs,
  faPhp,
  faPython,
  faReact,
  faTailwindCss,
  faTypescript,
} from '@fortawesome/free-brands-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

export const iconMap: Record<string, IconDefinition> = {
  code: faCode,
  figma: faFigma,
  computer: faComputer,
  palette: faPalette,
  html: faHtml5,
  css: faCss3Alt,
  js: faJs,
  react: faReact,
  tailwind: faTailwindCss,
  bootstrap: faBootstrap,
  git: faGitAlt,
  photoshop: faImage,
  adobexd: faPenRuler,
  etl: faArrowsSpin,
  aws: faAws,
  twilio: faComments,
  python: faPython,
  airflow: faDiagramProject,
  containerization: faCubes,
  docker: faDocker,
  lex: faRobot,
  typescript: faTypescript,
  vite: faBolt,
  styledcomponents: faPaintbrush,
  framermotion: faWandMagicSparkles,
  swiper: faImages,
  i18next: faLanguage,
  axios: faNetworkWired,
  eslint: faBroom,
  prettier: faAlignLeft,
  php: faPhp,
}
